services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://127.0.0.1:5000
    volumes:
      - ./mlruns:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlruns
      --host 0.0.0.0
      --port 5000
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin user
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default admin password
  alertmanager:
    image: prom/alertmanager
    ports:
    - "9093:9093"
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/config.yml
volumes: 
  grafana_data: