name: CI Workflow # The name of the workflow

on: # Defines the events that trigger the workflow
  push: # Trigger the workflow on pushes to specific branches
    branches:
      - main
  pull_request: # Trigger the workflow on pull requests to specific branches
    branches:
      - main


jobs:
  test: # Name of the job
    runs-on: ubuntu-latest # Specifies the operating system to run the job

    steps:
      - name: Checkout code # Step to clone the repository
        uses: actions/checkout@v4 # Official action to fetch repository content

      - name: Setup Project Environment
        uses: ./.github/actions/setup

      - name: Install Dependencies # Step to install project dependencies
        run: poetry install # Command to install dependencies from pyproject.toml

      - name: Run Tests # Step to run tests
        run: poetry run invoke test

      - name: Run Linting # Step to run linting
        run: poetry run invoke lint

      - name: Run Typing Checks # Step to check type annotations
        run: poetry run invoke type
